### PR TITLE
Feature: agency form flyout

### PR DESCRIPTION
**Pull request by zhwatts**
Adds ability to call a modal type Flyout from anywhere in the app via FlyoutContext, and then implements the "Create Agency Form" as a right flyout. 

Also fixes sizing issue with Agency List datagrid component, and refactors AgencyForm so it can be implemented in various other components. 

https://user-images.githubusercontent.com/9981733/107867364-5a807200-6e48-11eb-844f-681fd09e70d4.mov

### CODE REVIEW

**Comment by buihdk** [comment]
The Flyout doesn't work well with the dark mode at the moment
Screen Shot 2021-02-15 at 07 41 45

**Comment by buihdk** [comment]
I'm getting this error when I'm creating a new agency
Screen Shot 2021-02-15 at 07 45 26

**Comment by buihdk** [comment]
The user probably doesn't know why the `Create Agency` button in the Flyout is disabled by default. They may have to guess that they have to fill in all the fields in order to enable the button. 

Should we:
- Enable the `Create Agency` button by default so that when it is clicked, it will display validation errors to show which fields are required to be filled.
- Display asterisk to mark required fields so the user knows that they have to fill in all the required fields to proceed to the next step.

**Comment by zhwatts** [comment]
> The Flyout doesn't work well with the dark mode at the moment

refactored this to use Redux instead of useContext. Also made global theme available to the flyout component

> I'm getting this error when I'm creating a new agency
This PR does not include integrating the form component with the page actions controller... I'll do that in a separate PR

**Review by buihdk — APPROVED** [review]

**Pull request merged**
